Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ozhar_hasfarim.Models;
using ozhar_hasfarim.Service;
using ozhar_hasfarim.ViewModels;

namespace ozhar_hasfarim.Controllers
{
    public class LibraryController : Controller
    {
        private readonly ILibraryService _libraryService;

        public LibraryController(ILibraryService libraryService)
        {
            _libraryService = libraryService;
        }

        public async Task<IActionResult> Index() =>
            View(await _libraryService.GetAllLibrary());

        public async Task<IActionResult> Details(long id)
        {
            LibraryModel? library = await _libraryService.GetLibraryByID(id);

            return (library == null) ?
                RedirectToAction("Index") :
                View(new LibraryVM()
                {
                    Id = library.Id,
                    Genre = library.Genre,
                });
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(LibraryVM libraryVM)
        {
            try
            {
            var model = await _libraryService.CreateLibrary(libraryVM);
            libraryVM.Id = model.Id;
                return View("Details", libraryVM);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(libraryVM);
            }
        }

        public async Task<IActionResult> Delete(long id)
        {
            LibraryModel? library = await _libraryService.GetLibraryByID(id);
            if (library == null)
            {
                return NotFound();
            }

            return View(library);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            LibraryModel? library = await _libraryService.GetLibraryByID(id);
            if (library != null)
            {
                _libraryService.DeleteLibrary(library);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ShelfController.cs
using Microsoft.AspNetCore.Mvc;
using ozhar_hasfarim.Models;
using ozhar_hasfarim.Service;
using ozhar_hasfarim.ViewModels;

namespace ozhar_hasfarim.Controllers
{
    public class ShelfController : Controller
    {
        private long _LibraryId;
        private readonly IShelfService _shelfService;
        public ShelfController(IShelfService shelfService)
        {
            _shelfService = shelfService;
        }
        public IActionResult Index(long libraryId)
        {
            var shelfVMs = _shelfService.GetAllShelvesByLibrary(libraryId);
            ViewBag.LibraryId = libraryId;
            return View(shelfVMs);
        }

        public async Task<IActionResult> Details(long id, long libraryId)
        {
            ShelfModel? shelf = await _shelfService.GetShelfByID(id);

            return (shelf == null) ?
                RedirectToAction("Index", new { id = libraryId }) :
                View(new ShelfVM()
                {
                    Id = shelf.Id,
                    Height = shelf.Height,
                    Width = shelf.Width,
                    LibraryId = shelf.LibraryId
                });
        }

        public IActionResult Create(long libraryId) 
        {
            ShelfVM shelfVM = new () { LibraryId = libraryId };
            return View(shelfVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ShelfVM shelf)
        {
            var model = await _shelfService.CreateShelf(shelf); ;
            shelf.Id = model.Id;
            return View("Details", shelf);
        }

        public async Task<IActionResult> Delete(long id)
        {
            ShelfModel? shelf = await _shelfService.GetShelfByID(id);
            if (shelf == null)
            {
                return NotFound();
            }
            return View(shelf);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id, long libraryId)
        {
            ShelfModel? shelf = await _shelfService.GetShelfByID(id);
            if (shelf != null)
            {
                _shelfService.DeleteShelf(shelf);
            }
            return RedirectToAction("Index", new { libraryId = libraryId });
        }
    }
}

Views/Library/Create.cshtml
@model ozhar_hasfarim.ViewModels.LibraryVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create new library</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="Genre" class="form-control">
                    <option value="Tora">תורה</option>
                    <option value="Halacha">הלכה</option>
                    <option value="Chasidut">חסידות</option>
                    <option value="Musar">מוסר</option>
                    <option value="Hagut">הגות</option>
                    <option value="Machshava">מחשבה</option>
                    <option value="Kabala">קבלה</option>
                    <option value="Chinuch">חינוך</option>
                    <option value="Shonot">שונות</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Library/Delete.cshtml
@model ozhar_hasfarim.Models.LibraryModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Library</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LibraryModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Library/Details.cshtml
@model ozhar_hasfarim.ViewModels.LibraryVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details of library</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Shelves in library", "Index", "Shelf", new { LibraryId = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Library/Index.cshtml
@model IEnumerable<ozhar_hasfarim.ViewModels.LibraryVM>;

@{
    ViewData["Title"] = "Index";
}

<h1>Librarys</h1>

<p>
    <a asp-action="Create">Create New library</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Shelves in library", "Index", "Shelf", new { LibraryId = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>