Controllers/BooksSetController.cs
using Microsoft.AspNetCore.Mvc;
using ozhar_hasfarim.Models;
using ozhar_hasfarim.Service;
using ozhar_hasfarim.ViewModels;

namespace ozhar_hasfarim.Controllers
{
    public class BooksSetController : Controller
    {
        private readonly IBooksSetService _booksSetService;
        public BooksSetController(IBooksSetService booksSetService)
        {
            _booksSetService = booksSetService;
        }
        public IActionResult Index(long shelfId)
        {
            var booksSetVM = _booksSetService.GetAllBooksSetsByShlfId(shelfId);
            ViewBag.ShelfId = shelfId;
            return View(booksSetVM);
        }

        public async Task<IActionResult> Details(long id, long shelfId)
        {
            BooksSetModel? booksSet = await _booksSetService.GetBooksSetByBookSetId(id);

            return (booksSet == null) ?
                RedirectToAction("Index", shelfId) :
                View(new BooksSetVM()
                {
                    Id = booksSet.Id,
                    Name = booksSet.Name,
                    ShelfId = shelfId
                });
        }

        public IActionResult Create(long shelfId)
        {
            BooksSetVM booksSetVM = new() { ShelfId = shelfId };
            return View(booksSetVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BooksSetVM booksSetVM)
        {
            var model = await _booksSetService.CreateBookSet(booksSetVM); ;
            booksSetVM.Id = model.Id;
            return View("Details", booksSetVM);
        }

        public async Task<IActionResult> Delete(long id)
        {
            BooksSetModel? booksSet = await _booksSetService.GetBooksSetByBookSetId(id);
            if (booksSet == null)
            {
                return NotFound();
            }
            return View(booksSet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id, long shelfId)
        {
            BooksSetModel? booksSet = await _booksSetService.GetBooksSetByBookSetId(id);
            if (booksSet != null)
            {
                _booksSetService.DeleteBookSet(booksSet);
            }
            return RedirectToAction("Index", new { shelfId });
        }
    }
}

Controllers/ShelfController.cs
using Microsoft.AspNetCore.Mvc;
using ozhar_hasfarim.Models;
using ozhar_hasfarim.Service;
using ozhar_hasfarim.ViewModels;

namespace ozhar_hasfarim.Controllers
{
    public class ShelfController : Controller
    {
        private long _LibraryId;
        private readonly IShelfService _shelfService;
        public ShelfController(IShelfService shelfService)
        {
            _shelfService = shelfService;
        }
        public IActionResult Index(long libraryId)
        {
            var shelfVMs = _shelfService.GetAllShelvesByLibrary(libraryId);
            ViewBag.LibraryId = libraryId;
            return View(shelfVMs);
        }

        public async Task<IActionResult> Details(long id, long libraryId)
        {
            ShelfModel? shelf = await _shelfService.GetShelfByID(id);

            return (shelf == null) ?
                RedirectToAction("Index", new { id = libraryId }) :
                View(new ShelfVM()
                {
                    Id = shelf.Id,
                    Height = shelf.Height,
                    Width = shelf.Width,
                    LibraryId = shelf.LibraryId
                });
        }

        public IActionResult Create(long libraryId) 
        {
            ShelfVM shelfVM = new () { LibraryId = libraryId };
            return View(shelfVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ShelfVM shelf)
        {
            var model = await _shelfService.CreateShelf(shelf); ;
            shelf.Id = model.Id;
            return View("Details", shelf);
        }

        public async Task<IActionResult> Delete(long id)
        {
            ShelfModel? shelf = await _shelfService.GetShelfByID(id);
            if (shelf == null)
            {
                return NotFound();
            }
            return View(shelf);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id, long libraryId)
        {
            ShelfModel? shelf = await _shelfService.GetShelfByID(id);
            if (shelf != null)
            {
                _shelfService.DeleteShelf(shelf);
            }
            return RedirectToAction("Index", new { libraryId = libraryId });
        }
    }
}

Views/Shelf/Create.cshtml
@model ozhar_hasfarim.ViewModels.ShelfVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create new shelf</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="LibraryId" class="form-control"  value="@Model.LibraryId" hidden/>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index", new { libraryId = Model.LibraryId }) |
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shelf/Delete.cshtml
@model ozhar_hasfarim.Models.ShelfModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete shelf</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Library)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LibraryId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        @Html.HiddenFor(m => m.LibraryId)
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Back to List", "Index", new { libraryId = Model.LibraryId })
    </form>
</div>

Views/Shelf/Details.cshtml
@model ozhar_hasfarim.ViewModels.ShelfVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details of shelf</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id })|
    @Html.ActionLink("Back to List", "Index", new { libraryId = Model.LibraryId }) |
    @Html.ActionLink("Sets in shelf", "Index", "BookSet", new { shelfId = Model.Id })
</div>

Views/Shelf/Index.cshtml
@model IEnumerable<ozhar_hasfarim.ViewModels.ShelfVM>;

@{
    ViewData["Title"] = "Index";
}

<h1>Shelves in library num @ViewBag.LibraryId</h1>

<p>
    @Html.ActionLink(
        "Create new shelf", 
        "Create", 
        new { libraryId = ViewBag.LibraryId }
    )
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id, libraryId = ViewBag.LibraryId  }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
                @Html.ActionLink("Sets in Shelf", "Index", "BooksSet", new { shelfId = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>